#!/bin/bash
cd "$(dirname $0)"/..

if [ -e .env/bin/activate ]; then
    . .env/bin/activate
fi
export PYTHONPATH="$(pwd)/lib:$PYTHONPATH"

exec bash --init-file <(echo '. ~/.bashrc; PS1="MOG $PS1"') -i
