FROM ubuntu:devel
MAINTAINER Bjarni R. Einarsson <bre@mailpile.is>

RUN apt-get update \
    && apt install -y git curl vim \
        python3-cryptography \
        python3-urwid \
        python3-websockets \
        python3-numpy \
        python3-appdirs \
        python3-setproctitle

RUN curl 'https://lists.apache.org/api/mbox.lua?list=dev@age.apache.org&date=2022-01' \
        >/root/test.mbx

VOLUME /mnt/code
WORKDIR /root
CMD /mnt/code/tools/docker-internal.sh
