#!/bin/bash
if [ "$MOGGIE_URL" = "" ]; then
  if [ "$MOGGIE_TOKEN" = "" ]; then
    URL=$(cat ~/.local/share/Moggie/default/workers/app.url)
  else
    URL=$(cut -f1-3 -d/ ~/.local/share/Moggie/default/workers/app.url)/$MOGGIE_TOKEN
  fi
else
  URL="$MOGGIE_URL"
fi

APP=$1
shift

(if [[ "$*" =~ '--batch' ]]; then
    export STDIN_CONTENT="--stdin=$(</dev/stdin)"
fi
for ARG in "$@" "$STDIN_CONTENT"; do
    echo -n "$ARG"
    echo -n -e '\0'
done) \
|curl -sfN ${MOGGIE_CURL_ARGS:-} -H "Accept: ${MOGGIE_ACCEPT:-text/plain}" -F 'argz=<-' $URL/cli/$APP \
